# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_4_1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 671)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_40 = QtWidgets.QLabel(self.tab_4)
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("banner.png"))
        self.label_40.setObjectName("label_40")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_40)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setObjectName("label_39")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_39)
        self.ExperimenterName = QtWidgets.QLineEdit(self.tab_4)
        self.ExperimenterName.setObjectName("ExperimenterName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ExperimenterName)
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setObjectName("label_41")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_41)
        self.DogName = QtWidgets.QLineEdit(self.tab_4)
        self.DogName.setObjectName("DogName")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.DogName)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.formLayout_2)
        self.Submit1 = QtWidgets.QPushButton(self.tab_4)
        self.Submit1.setObjectName("Submit1")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Submit1)
        self.label_42 = QtWidgets.QLabel(self.tab_4)
        self.label_42.setObjectName("label_42")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_42)
        self.TrainingLevel = QtWidgets.QComboBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TrainingLevel.setFont(font)
        self.TrainingLevel.setObjectName("TrainingLevel")
        self.TrainingLevel.addItem("")
        self.TrainingLevel.addItem("")
        self.TrainingLevel.addItem("")
        self.TrainingLevel.addItem("")
        self.TrainingLevel.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.TrainingLevel)
        self.gridLayout_9.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ConnectOlfactometers = QtWidgets.QPushButton(self.tab_8)
        self.ConnectOlfactometers.setObjectName("ConnectOlfactometers")
        self.gridLayout_7.addWidget(self.ConnectOlfactometers, 5, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_8)
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("banner.png"))
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 0, 0, 1, 2)
        self.OlfactometerList = QtWidgets.QListWidget(self.tab_8)
        self.OlfactometerList.setObjectName("OlfactometerList")
        self.gridLayout_7.addWidget(self.OlfactometerList, 3, 0, 1, 1)
        self.BLEScan = QtWidgets.QPushButton(self.tab_8)
        self.BLEScan.setObjectName("BLEScan")
        self.gridLayout_7.addWidget(self.BLEScan, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_7.addWidget(self.label_43, 2, 0, 1, 1)
        self.OlfLabel_1 = QtWidgets.QLabel(self.tab_8)
        self.OlfLabel_1.setObjectName("OlfLabel_1")
        self.gridLayout_7.addWidget(self.OlfLabel_1, 10, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_47 = QtWidgets.QLabel(self.tab_9)
        self.label_47.setObjectName("label_47")
        self.gridLayout_10.addWidget(self.label_47, 1, 0, 1, 1)
        self.V5On = QtWidgets.QCheckBox(self.tab_9)
        self.V5On.setObjectName("V5On")
        self.gridLayout_10.addWidget(self.V5On, 5, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.tab_9)
        self.label_54.setObjectName("label_54")
        self.gridLayout_10.addWidget(self.label_54, 8, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_9)
        self.label_55.setObjectName("label_55")
        self.gridLayout_10.addWidget(self.label_55, 9, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.tab_9)
        self.label_58.setObjectName("label_58")
        self.gridLayout_10.addWidget(self.label_58, 12, 0, 1, 1)
        self.V1On = QtWidgets.QCheckBox(self.tab_9)
        self.V1On.setObjectName("V1On")
        self.gridLayout_10.addWidget(self.V1On, 1, 1, 1, 1)
        self.V6On = QtWidgets.QCheckBox(self.tab_9)
        self.V6On.setObjectName("V6On")
        self.gridLayout_10.addWidget(self.V6On, 6, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.tab_9)
        self.label_49.setObjectName("label_49")
        self.gridLayout_10.addWidget(self.label_49, 3, 0, 1, 1)
        self.V8On = QtWidgets.QCheckBox(self.tab_9)
        self.V8On.setObjectName("V8On")
        self.gridLayout_10.addWidget(self.V8On, 8, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_9)
        self.label_57.setObjectName("label_57")
        self.gridLayout_10.addWidget(self.label_57, 11, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_9)
        self.label_50.setObjectName("label_50")
        self.gridLayout_10.addWidget(self.label_50, 4, 0, 1, 1)
        self.V3On = QtWidgets.QCheckBox(self.tab_9)
        self.V3On.setObjectName("V3On")
        self.gridLayout_10.addWidget(self.V3On, 3, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_9)
        self.label_56.setObjectName("label_56")
        self.gridLayout_10.addWidget(self.label_56, 10, 0, 1, 1)
        self.V7On = QtWidgets.QCheckBox(self.tab_9)
        self.V7On.setObjectName("V7On")
        self.gridLayout_10.addWidget(self.V7On, 7, 1, 1, 1)
        self.V11On = QtWidgets.QCheckBox(self.tab_9)
        self.V11On.setObjectName("V11On")
        self.gridLayout_10.addWidget(self.V11On, 11, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab_9)
        self.label_52.setObjectName("label_52")
        self.gridLayout_10.addWidget(self.label_52, 6, 0, 1, 1)
        self.V2On = QtWidgets.QCheckBox(self.tab_9)
        self.V2On.setObjectName("V2On")
        self.gridLayout_10.addWidget(self.V2On, 2, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_9)
        self.label_53.setObjectName("label_53")
        self.gridLayout_10.addWidget(self.label_53, 7, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_9)
        self.label_48.setObjectName("label_48")
        self.gridLayout_10.addWidget(self.label_48, 2, 0, 1, 1)
        self.V4On = QtWidgets.QCheckBox(self.tab_9)
        self.V4On.setObjectName("V4On")
        self.gridLayout_10.addWidget(self.V4On, 4, 1, 1, 1)
        self.V9On = QtWidgets.QCheckBox(self.tab_9)
        self.V9On.setObjectName("V9On")
        self.gridLayout_10.addWidget(self.V9On, 9, 1, 1, 1)
        self.V10On = QtWidgets.QCheckBox(self.tab_9)
        self.V10On.setObjectName("V10On")
        self.gridLayout_10.addWidget(self.V10On, 10, 1, 1, 1)
        self.V12On = QtWidgets.QCheckBox(self.tab_9)
        self.V12On.setObjectName("V12On")
        self.gridLayout_10.addWidget(self.V12On, 12, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_9)
        self.label_51.setObjectName("label_51")
        self.gridLayout_10.addWidget(self.label_51, 5, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 1, 1, 1, 1)
        self.OdorsOn = QtWidgets.QPushButton(self.tab_9)
        self.OdorsOn.setObjectName("OdorsOn")
        self.gridLayout_11.addWidget(self.OdorsOn, 2, 1, 1, 1)
        self.OdorsOff = QtWidgets.QPushButton(self.tab_9)
        self.OdorsOff.setObjectName("OdorsOff")
        self.gridLayout_11.addWidget(self.OdorsOff, 2, 2, 1, 1)
        self.Terminate = QtWidgets.QPushButton(self.tab_9)
        self.Terminate.setObjectName("Terminate")
        self.gridLayout_11.addWidget(self.Terminate, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Odor1 = QtWidgets.QComboBox(self.tab_10)
        self.Odor1.setObjectName("Odor1")
        self.gridLayout.addWidget(self.Odor1, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_10)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_10)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_10)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.Odor2 = QtWidgets.QComboBox(self.tab_10)
        self.Odor2.setObjectName("Odor2")
        self.gridLayout.addWidget(self.Odor2, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_10)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 5, 1, 1)
        self.Odor4 = QtWidgets.QComboBox(self.tab_10)
        self.Odor4.setObjectName("Odor4")
        self.gridLayout.addWidget(self.Odor4, 1, 4, 1, 1)
        self.Odor5 = QtWidgets.QComboBox(self.tab_10)
        self.Odor5.setObjectName("Odor5")
        self.gridLayout.addWidget(self.Odor5, 1, 5, 1, 1)
        self.TargDist_5 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_5.setObjectName("TargDist_5")
        self.TargDist_5.addItem("")
        self.TargDist_5.addItem("")
        self.TargDist_5.addItem("")
        self.gridLayout.addWidget(self.TargDist_5, 2, 5, 1, 1)
        self.TargDist_2 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_2.setObjectName("TargDist_2")
        self.TargDist_2.addItem("")
        self.TargDist_2.addItem("")
        self.TargDist_2.addItem("")
        self.TargDist_2.addItem("")
        self.gridLayout.addWidget(self.TargDist_2, 2, 2, 1, 1)
        self.OdorWeights_2 = QtWidgets.QComboBox(self.tab_10)
        self.OdorWeights_2.setObjectName("OdorWeights_2")
        self.OdorWeights_2.addItem("")
        self.OdorWeights_2.addItem("")
        self.OdorWeights_2.addItem("")
        self.OdorWeights_2.addItem("")
        self.gridLayout.addWidget(self.OdorWeights_2, 3, 2, 1, 1)
        self.TargDist_6 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_6.setObjectName("TargDist_6")
        self.TargDist_6.addItem("")
        self.TargDist_6.addItem("")
        self.gridLayout.addWidget(self.TargDist_6, 2, 6, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_10)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 3, 0, 1, 1)
        self.TargDist_4 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_4.setObjectName("TargDist_4")
        self.TargDist_4.addItem("")
        self.TargDist_4.addItem("")
        self.TargDist_4.addItem("")
        self.TargDist_4.addItem("")
        self.gridLayout.addWidget(self.TargDist_4, 2, 4, 1, 1)
        self.TargDist_3 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_3.setObjectName("TargDist_3")
        self.TargDist_3.addItem("")
        self.TargDist_3.addItem("")
        self.TargDist_3.addItem("")
        self.TargDist_3.addItem("")
        self.gridLayout.addWidget(self.TargDist_3, 2, 3, 1, 1)
        self.OdorWeights_1 = QtWidgets.QComboBox(self.tab_10)
        self.OdorWeights_1.setObjectName("OdorWeights_1")
        self.OdorWeights_1.addItem("")
        self.OdorWeights_1.addItem("")
        self.OdorWeights_1.addItem("")
        self.gridLayout.addWidget(self.OdorWeights_1, 3, 1, 1, 1)
        self.OdorWeights_3 = QtWidgets.QComboBox(self.tab_10)
        self.OdorWeights_3.setObjectName("OdorWeights_3")
        self.OdorWeights_3.addItem("")
        self.OdorWeights_3.addItem("")
        self.OdorWeights_3.addItem("")
        self.OdorWeights_3.addItem("")
        self.gridLayout.addWidget(self.OdorWeights_3, 3, 3, 1, 1)
        self.TargDist_1 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_1.setObjectName("TargDist_1")
        self.TargDist_1.addItem("")
        self.TargDist_1.addItem("")
        self.TargDist_1.addItem("")
        self.gridLayout.addWidget(self.TargDist_1, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_10)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_10)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.Odor3 = QtWidgets.QComboBox(self.tab_10)
        self.Odor3.setObjectName("Odor3")
        self.gridLayout.addWidget(self.Odor3, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_10)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 3, 1, 1)
        self.Odor6 = QtWidgets.QComboBox(self.tab_10)
        self.Odor6.setObjectName("Odor6")
        self.gridLayout.addWidget(self.Odor6, 1, 6, 1, 1)
        self.OdorWeights_4 = QtWidgets.QComboBox(self.tab_10)
        self.OdorWeights_4.setObjectName("OdorWeights_4")
        self.OdorWeights_4.addItem("")
        self.OdorWeights_4.addItem("")
        self.OdorWeights_4.addItem("")
        self.OdorWeights_4.addItem("")
        self.gridLayout.addWidget(self.OdorWeights_4, 3, 4, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.tab_10)
        self.label_74.setObjectName("label_74")
        self.gridLayout.addWidget(self.label_74, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem6, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem7, 4, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_72 = QtWidgets.QLabel(self.tab_10)
        self.label_72.setObjectName("label_72")
        self.gridLayout_13.addWidget(self.label_72, 0, 1, 1, 1)
        self.Odor10 = QtWidgets.QComboBox(self.tab_10)
        self.Odor10.setObjectName("Odor10")
        self.gridLayout_13.addWidget(self.Odor10, 1, 4, 1, 1)
        self.Odor7 = QtWidgets.QComboBox(self.tab_10)
        self.Odor7.setObjectName("Odor7")
        self.gridLayout_13.addWidget(self.Odor7, 1, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.tab_10)
        self.label_73.setObjectName("label_73")
        self.gridLayout_13.addWidget(self.label_73, 0, 5, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.tab_10)
        self.label_71.setObjectName("label_71")
        self.gridLayout_13.addWidget(self.label_71, 0, 6, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.tab_10)
        self.label_70.setObjectName("label_70")
        self.gridLayout_13.addWidget(self.label_70, 0, 4, 1, 1)
        self.Odor11 = QtWidgets.QComboBox(self.tab_10)
        self.Odor11.setObjectName("Odor11")
        self.gridLayout_13.addWidget(self.Odor11, 1, 5, 1, 1)
        self.Odor8 = QtWidgets.QComboBox(self.tab_10)
        self.Odor8.setObjectName("Odor8")
        self.gridLayout_13.addWidget(self.Odor8, 1, 2, 1, 1)
        self.TargDist_8 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_8.setObjectName("TargDist_8")
        self.TargDist_8.addItem("")
        self.TargDist_8.addItem("")
        self.gridLayout_13.addWidget(self.TargDist_8, 2, 2, 1, 1)
        self.TargDist_9 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_9.setObjectName("TargDist_9")
        self.TargDist_9.addItem("")
        self.TargDist_9.addItem("")
        self.TargDist_9.addItem("")
        self.gridLayout_13.addWidget(self.TargDist_9, 2, 3, 1, 1)
        self.TargDist_11 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_11.setObjectName("TargDist_11")
        self.TargDist_11.addItem("")
        self.TargDist_11.addItem("")
        self.TargDist_11.addItem("")
        self.gridLayout_13.addWidget(self.TargDist_11, 2, 5, 1, 1)
        self.TargDist_12 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_12.setObjectName("TargDist_12")
        self.TargDist_12.addItem("")
        self.TargDist_12.addItem("")
        self.TargDist_12.addItem("")
        self.TargDist_12.addItem("")
        self.gridLayout_13.addWidget(self.TargDist_12, 2, 6, 1, 1)
        self.TargDist_10 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_10.setObjectName("TargDist_10")
        self.TargDist_10.addItem("")
        self.TargDist_10.addItem("")
        self.TargDist_10.addItem("")
        self.gridLayout_13.addWidget(self.TargDist_10, 2, 4, 1, 1)
        self.TargDist_7 = QtWidgets.QComboBox(self.tab_10)
        self.TargDist_7.setObjectName("TargDist_7")
        self.TargDist_7.addItem("")
        self.gridLayout_13.addWidget(self.TargDist_7, 2, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.tab_10)
        self.label_77.setObjectName("label_77")
        self.gridLayout_13.addWidget(self.label_77, 0, 3, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.tab_10)
        self.label_76.setObjectName("label_76")
        self.gridLayout_13.addWidget(self.label_76, 0, 2, 1, 1)
        self.Odor9 = QtWidgets.QComboBox(self.tab_10)
        self.Odor9.setObjectName("Odor9")
        self.gridLayout_13.addWidget(self.Odor9, 1, 3, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.tab_10)
        self.label_75.setObjectName("label_75")
        self.gridLayout_13.addWidget(self.label_75, 2, 0, 1, 1)
        self.Odor12 = QtWidgets.QComboBox(self.tab_10)
        self.Odor12.setObjectName("Odor12")
        self.gridLayout_13.addWidget(self.Odor12, 1, 6, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.tab_10)
        self.label_78.setObjectName("label_78")
        self.gridLayout_13.addWidget(self.label_78, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_13, 3, 0, 1, 1)
        self.EditOdorList = QtWidgets.QPushButton(self.tab_10)
        self.EditOdorList.setObjectName("EditOdorList")
        self.gridLayout_12.addWidget(self.EditOdorList, 5, 0, 1, 1)
        self.SubmitOdors = QtWidgets.QPushButton(self.tab_10)
        self.SubmitOdors.setObjectName("SubmitOdors")
        self.gridLayout_12.addWidget(self.SubmitOdors, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.Notes = QtWidgets.QLineEdit(self.tab)
        self.Notes.setObjectName("Notes")
        self.gridLayout_2.addWidget(self.Notes, 12, 1, 1, 1)
        self.DaySession = QtWidgets.QSpinBox(self.tab)
        self.DaySession.setObjectName("DaySession")
        self.gridLayout_2.addWidget(self.DaySession, 5, 1, 1, 1)
        self.AlertTime_2 = QtWidgets.QDoubleSpinBox(self.tab)
        self.AlertTime_2.setProperty("value", 0.0)
        self.AlertTime_2.setObjectName("AlertTime_2")
        self.gridLayout_2.addWidget(self.AlertTime_2, 2, 1, 1, 1)
        self.TrialTime = QtWidgets.QSpinBox(self.tab)
        self.TrialTime.setProperty("value", 45)
        self.TrialTime.setObjectName("TrialTime")
        self.gridLayout_2.addWidget(self.TrialTime, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.AlertTime = QtWidgets.QDoubleSpinBox(self.tab)
        self.AlertTime.setProperty("value", 4.0)
        self.AlertTime.setObjectName("AlertTime")
        self.gridLayout_2.addWidget(self.AlertTime, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 3, 0, 1, 1)
        self.NumberofTrials = QtWidgets.QComboBox(self.tab)
        self.NumberofTrials.setObjectName("NumberofTrials")
        self.NumberofTrials.addItem("")
        self.NumberofTrials.addItem("")
        self.NumberofTrials.addItem("")
        self.NumberofTrials.addItem("")
        self.NumberofTrials.addItem("")
        self.NumberofTrials.addItem("")
        self.gridLayout_2.addWidget(self.NumberofTrials, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.GenProbes = QtWidgets.QComboBox(self.tab)
        self.GenProbes.setObjectName("GenProbes")
        self.GenProbes.addItem("")
        self.GenProbes.addItem("")
        self.GenProbes.addItem("")
        self.GenProbes.addItem("")
        self.GenProbes.addItem("")
        self.gridLayout_2.addWidget(self.GenProbes, 5, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 3, 1, 1)
        self.OdorPrev = QtWidgets.QComboBox(self.tab)
        self.OdorPrev.setObjectName("OdorPrev")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.OdorPrev.addItem("")
        self.gridLayout_2.addWidget(self.OdorPrev, 1, 4, 1, 1)
        self.AutoScore = QtWidgets.QComboBox(self.tab)
        self.AutoScore.setObjectName("AutoScore")
        self.AutoScore.addItem("")
        self.AutoScore.addItem("")
        self.gridLayout_2.addWidget(self.AutoScore, 6, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 3, 1, 1)
        self.ReinforceTargets = QtWidgets.QComboBox(self.tab)
        self.ReinforceTargets.setObjectName("ReinforceTargets")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.ReinforceTargets.addItem("")
        self.gridLayout_2.addWidget(self.ReinforceTargets, 3, 4, 1, 1)
        self.WaitforCorrect = QtWidgets.QComboBox(self.tab)
        self.WaitforCorrect.setObjectName("WaitforCorrect")
        self.WaitforCorrect.addItem("")
        self.WaitforCorrect.addItem("")
        self.gridLayout_2.addWidget(self.WaitforCorrect, 0, 4, 1, 1)
        self.Context = QtWidgets.QComboBox(self.tab)
        self.Context.setObjectName("Context")
        self.Context.addItem("")
        self.Context.addItem("")
        self.gridLayout_2.addWidget(self.Context, 4, 4, 1, 1)
        self.SaveSettings = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SaveSettings.setFont(font)
        self.SaveSettings.setObjectName("SaveSettings")
        self.gridLayout_2.addWidget(self.SaveSettings, 12, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 3, 1, 1)
        self.ReinforceBlanks = QtWidgets.QComboBox(self.tab)
        self.ReinforceBlanks.setObjectName("ReinforceBlanks")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.ReinforceBlanks.addItem("")
        self.gridLayout_2.addWidget(self.ReinforceBlanks, 2, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 7, 3, 1, 1)
        self.Session = QtWidgets.QSpinBox(self.tab)
        self.Session.setObjectName("Session")
        self.gridLayout_2.addWidget(self.Session, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 3, 1, 1)
        self.odorLine = QtWidgets.QComboBox(self.tab)
        self.odorLine.setObjectName("odorLine")
        self.odorLine.addItem("")
        self.odorLine.addItem("")
        self.odorLine.addItem("")
        self.odorLine.addItem("")
        self.odorLine.addItem("")
        self.odorLine.addItem("")
        self.gridLayout_2.addWidget(self.odorLine, 7, 4, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 12, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 6, 3, 1, 1)
        self.HandlerBlind = QtWidgets.QComboBox(self.tab)
        self.HandlerBlind.setObjectName("HandlerBlind")
        self.HandlerBlind.addItem("")
        self.HandlerBlind.addItem("")
        self.gridLayout_2.addWidget(self.HandlerBlind, 6, 1, 1, 1)
        self.airLine = QtWidgets.QComboBox(self.tab)
        self.airLine.setObjectName("airLine")
        self.airLine.addItem("")
        self.airLine.addItem("")
        self.airLine.addItem("")
        self.airLine.addItem("")
        self.airLine.addItem("")
        self.airLine.addItem("")
        self.airLine.addItem("")
        self.airLine.addItem("")
        self.airLine.addItem("")
        self.gridLayout_2.addWidget(self.airLine, 7, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 5, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 3, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem9, 2, 0, 1, 1)
        self.Submit = QtWidgets.QPushButton(self.tab)
        self.Submit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Submit.sizePolicy().hasHeightForWidth())
        self.Submit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Submit.setFont(font)
        self.Submit.setObjectName("Submit")
        self.gridLayout_14.addWidget(self.Submit, 3, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.response_2 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.response_2.setFont(font)
        self.response_2.setObjectName("response_2")
        self.gridLayout_4.addWidget(self.response_2, 0, 1, 1, 1)
        self.response_4 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.response_4.setFont(font)
        self.response_4.setObjectName("response_4")
        self.gridLayout_4.addWidget(self.response_4, 1, 0, 1, 1)
        self.response_1 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.response_1.setFont(font)
        self.response_1.setObjectName("response_1")
        self.gridLayout_4.addWidget(self.response_1, 0, 0, 1, 1)
        self.response_6 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.response_6.setFont(font)
        self.response_6.setObjectName("response_6")
        self.gridLayout_4.addWidget(self.response_6, 1, 2, 1, 1)
        self.response_3 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.response_3.setFont(font)
        self.response_3.setObjectName("response_3")
        self.gridLayout_4.addWidget(self.response_3, 0, 2, 1, 1)
        self.response_5 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.response_5.setFont(font)
        self.response_5.setObjectName("response_5")
        self.gridLayout_4.addWidget(self.response_5, 1, 1, 1, 1)
        self.response_7 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.response_7.setFont(font)
        self.response_7.setObjectName("response_7")
        self.gridLayout_4.addWidget(self.response_7, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 2, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 4, 0, 1, 4)
        self.trialNumber = QtWidgets.QLCDNumber(self.tab_2)
        self.trialNumber.setObjectName("trialNumber")
        self.gridLayout_6.addWidget(self.trialNumber, 0, 2, 1, 1)
        self.infoLabel = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.infoLabel.setFont(font)
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout_6.addWidget(self.infoLabel, 2, 0, 1, 1)
        self.Response_Box = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Response_Box.setFont(font)
        self.Response_Box.setObjectName("Response_Box")
        self.Response_Box.addItem("")
        self.Response_Box.addItem("")
        self.Response_Box.addItem("")
        self.Response_Box.addItem("")
        self.Response_Box.addItem("")
        self.Response_Box.addItem("")
        self.Response_Box.addItem("")
        self.gridLayout_6.addWidget(self.Response_Box, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Position1 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Position1.setFont(font)
        self.Position1.setObjectName("Position1")
        self.gridLayout_8.addWidget(self.Position1, 0, 0, 1, 1)
        self.Position3 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Position3.setFont(font)
        self.Position3.setObjectName("Position3")
        self.gridLayout_8.addWidget(self.Position3, 0, 1, 1, 1)
        self.Position1_2 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Position1_2.setFont(font)
        self.Position1_2.setObjectName("Position1_2")
        self.gridLayout_8.addWidget(self.Position1_2, 1, 0, 1, 1)
        self.Position1_3 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Position1_3.setFont(font)
        self.Position1_3.setObjectName("Position1_3")
        self.gridLayout_8.addWidget(self.Position1_3, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.tab_5)
        self.formLayout_6.setObjectName("formLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 6, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 3, 0, 1, 1)
        self.ResetOdors = QtWidgets.QPushButton(self.tab_5)
        self.ResetOdors.setObjectName("ResetOdors")
        self.gridLayout_3.addWidget(self.ResetOdors, 12, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 4, 0, 1, 1)
        self.NewOdor_1 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_1.setObjectName("NewOdor_1")
        self.gridLayout_3.addWidget(self.NewOdor_1, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 5, 0, 1, 1)
        self.NewOdor_2 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_2.setObjectName("NewOdor_2")
        self.gridLayout_3.addWidget(self.NewOdor_2, 1, 1, 1, 1)
        self.NewOdor_3 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_3.setObjectName("NewOdor_3")
        self.gridLayout_3.addWidget(self.NewOdor_3, 2, 1, 1, 1)
        self.NewOdor_5 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_5.setObjectName("NewOdor_5")
        self.gridLayout_3.addWidget(self.NewOdor_5, 4, 1, 1, 1)
        self.NewOdor_6 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_6.setObjectName("NewOdor_6")
        self.gridLayout_3.addWidget(self.NewOdor_6, 5, 1, 1, 1)
        self.NewOdor_4 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_4.setObjectName("NewOdor_4")
        self.gridLayout_3.addWidget(self.NewOdor_4, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.tab_5)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 10, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_5)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 9, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab_5)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 11, 0, 1, 1)
        self.NewOdor_7 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_7.setObjectName("NewOdor_7")
        self.gridLayout_3.addWidget(self.NewOdor_7, 6, 1, 1, 1)
        self.NewOdor_8 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_8.setObjectName("NewOdor_8")
        self.gridLayout_3.addWidget(self.NewOdor_8, 7, 1, 1, 1)
        self.NewOdor9 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor9.setObjectName("NewOdor9")
        self.gridLayout_3.addWidget(self.NewOdor9, 8, 1, 1, 1)
        self.NewOdor_10 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_10.setObjectName("NewOdor_10")
        self.gridLayout_3.addWidget(self.NewOdor_10, 9, 1, 1, 1)
        self.NewOdor_11 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_11.setObjectName("NewOdor_11")
        self.gridLayout_3.addWidget(self.NewOdor_11, 10, 1, 1, 1)
        self.NewOdor_12 = QtWidgets.QLineEdit(self.tab_5)
        self.NewOdor_12.setObjectName("NewOdor_12")
        self.gridLayout_3.addWidget(self.NewOdor_12, 11, 1, 1, 1)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_3)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem11, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsave_as_default = QtWidgets.QAction(MainWindow)
        self.actionsave_as_default.setObjectName("actionsave_as_default")
        self.actionset_directory = QtWidgets.QAction(MainWindow)
        self.actionset_directory.setObjectName("actionset_directory")
        self.actionset_data_folder = QtWidgets.QAction(MainWindow)
        self.actionset_data_folder.setObjectName("actionset_data_folder")
        self.menuFile.addAction(self.actionsave_as_default)
        self.menuFile.addAction(self.actionset_directory)
        self.menuFile.addAction(self.actionset_data_folder)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.TargDist_5.setCurrentIndex(0)
        self.TargDist_2.setCurrentIndex(0)
        self.TargDist_6.setCurrentIndex(0)
        self.TargDist_4.setCurrentIndex(0)
        self.TargDist_3.setCurrentIndex(0)
        self.TargDist_8.setCurrentIndex(0)
        self.TargDist_9.setCurrentIndex(0)
        self.TargDist_11.setCurrentIndex(0)
        self.TargDist_12.setCurrentIndex(0)
        self.TargDist_10.setCurrentIndex(0)
        self.OdorPrev.setCurrentIndex(0)
        self.ReinforceBlanks.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Experimenter Name</span></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Dog Name</span></p></body></html>"))
        self.Submit1.setText(_translate("MainWindow", "Submit "))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Paradigm</span></p></body></html>"))
        self.TrainingLevel.setItemText(0, _translate("MainWindow", "AFC"))
        self.TrainingLevel.setItemText(1, _translate("MainWindow", "Mixture"))
        self.TrainingLevel.setItemText(2, _translate("MainWindow", "Inter-Mixed"))
        self.TrainingLevel.setItemText(3, _translate("MainWindow", "Test"))
        self.TrainingLevel.setItemText(4, _translate("MainWindow", "Threshold"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Start"))
        self.ConnectOlfactometers.setText(_translate("MainWindow", "Connect Olfactometers"))
        self.BLEScan.setText(_translate("MainWindow", "Scan Olfactometers"))
        self.label_43.setText(_translate("MainWindow", "Scan Olfactometer"))
        self.OlfLabel_1.setText(_translate("MainWindow", "Status Updates"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Connect"))
        self.label_47.setText(_translate("MainWindow", "Valve 1"))
        self.V5On.setText(_translate("MainWindow", "On"))
        self.label_54.setText(_translate("MainWindow", "Valve 8"))
        self.label_55.setText(_translate("MainWindow", "Valve 9"))
        self.label_58.setText(_translate("MainWindow", "Valve 12"))
        self.V1On.setText(_translate("MainWindow", "On"))
        self.V6On.setText(_translate("MainWindow", "On"))
        self.label_49.setText(_translate("MainWindow", "Valve 3"))
        self.V8On.setText(_translate("MainWindow", "On"))
        self.label_57.setText(_translate("MainWindow", "Valve 11"))
        self.label_50.setText(_translate("MainWindow", "Valve 4"))
        self.V3On.setText(_translate("MainWindow", "On"))
        self.label_56.setText(_translate("MainWindow", "Valve 10"))
        self.V7On.setText(_translate("MainWindow", "On"))
        self.V11On.setText(_translate("MainWindow", "On"))
        self.label_52.setText(_translate("MainWindow", "Valve 6"))
        self.V2On.setText(_translate("MainWindow", "On"))
        self.label_53.setText(_translate("MainWindow", "Valve 7"))
        self.label_48.setText(_translate("MainWindow", "Valve 2"))
        self.V4On.setText(_translate("MainWindow", "On"))
        self.V9On.setText(_translate("MainWindow", "On"))
        self.V10On.setText(_translate("MainWindow", "On"))
        self.V12On.setText(_translate("MainWindow", "On"))
        self.label_51.setText(_translate("MainWindow", "Valve 5"))
        self.OdorsOn.setText(_translate("MainWindow", "Turn On"))
        self.OdorsOff.setText(_translate("MainWindow", "Odors Off"))
        self.Terminate.setText(_translate("MainWindow", "Terminate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Test"))
        self.label_14.setText(_translate("MainWindow", "Valve 4"))
        self.label_22.setText(_translate("MainWindow", "Valve 6"))
        self.label_9.setText(_translate("MainWindow", "Valve 1"))
        self.label_21.setText(_translate("MainWindow", "Valve 5"))
        self.TargDist_5.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_5.setItemText(1, _translate("MainWindow", "Generalization Test"))
        self.TargDist_5.setItemText(2, _translate("MainWindow", "None"))
        self.TargDist_2.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_2.setItemText(1, _translate("MainWindow", "Target"))
        self.TargDist_2.setItemText(2, _translate("MainWindow", "Mix Target"))
        self.TargDist_2.setItemText(3, _translate("MainWindow", "Probe"))
        self.OdorWeights_2.setItemText(0, _translate("MainWindow", "0"))
        self.OdorWeights_2.setItemText(1, _translate("MainWindow", "1"))
        self.OdorWeights_2.setItemText(2, _translate("MainWindow", "2"))
        self.OdorWeights_2.setItemText(3, _translate("MainWindow", "3"))
        self.TargDist_6.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_6.setItemText(1, _translate("MainWindow", "None"))
        self.label_29.setText(_translate("MainWindow", "Target Weights"))
        self.TargDist_4.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_4.setItemText(1, _translate("MainWindow", "Target"))
        self.TargDist_4.setItemText(2, _translate("MainWindow", "Mix Target"))
        self.TargDist_4.setItemText(3, _translate("MainWindow", "None"))
        self.TargDist_3.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_3.setItemText(1, _translate("MainWindow", "Target"))
        self.TargDist_3.setItemText(2, _translate("MainWindow", "Mix Target"))
        self.TargDist_3.setItemText(3, _translate("MainWindow", "None"))
        self.OdorWeights_1.setItemText(0, _translate("MainWindow", "1"))
        self.OdorWeights_1.setItemText(1, _translate("MainWindow", "2"))
        self.OdorWeights_1.setItemText(2, _translate("MainWindow", "3"))
        self.OdorWeights_3.setItemText(0, _translate("MainWindow", "0"))
        self.OdorWeights_3.setItemText(1, _translate("MainWindow", "1"))
        self.OdorWeights_3.setItemText(2, _translate("MainWindow", "2"))
        self.OdorWeights_3.setItemText(3, _translate("MainWindow", "3"))
        self.TargDist_1.setItemText(0, _translate("MainWindow", "Target"))
        self.TargDist_1.setItemText(1, _translate("MainWindow", "Mix Target"))
        self.TargDist_1.setItemText(2, _translate("MainWindow", "Distractor"))
        self.label_28.setText(_translate("MainWindow", "Target or Distractor"))
        self.label_10.setText(_translate("MainWindow", "Valve 2"))
        self.label_11.setText(_translate("MainWindow", "Valve 3"))
        self.OdorWeights_4.setItemText(0, _translate("MainWindow", "0"))
        self.OdorWeights_4.setItemText(1, _translate("MainWindow", "1"))
        self.OdorWeights_4.setItemText(2, _translate("MainWindow", "2"))
        self.OdorWeights_4.setItemText(3, _translate("MainWindow", "3"))
        self.label_74.setText(_translate("MainWindow", "Odor"))
        self.label_72.setText(_translate("MainWindow", "Valve 7"))
        self.label_73.setText(_translate("MainWindow", "Valve 11"))
        self.label_71.setText(_translate("MainWindow", "Valve 12"))
        self.label_70.setText(_translate("MainWindow", "Valve 10"))
        self.TargDist_8.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_8.setItemText(1, _translate("MainWindow", "Probe"))
        self.TargDist_9.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_9.setItemText(1, _translate("MainWindow", "Distractor Mix"))
        self.TargDist_9.setItemText(2, _translate("MainWindow", "None"))
        self.TargDist_11.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_11.setItemText(1, _translate("MainWindow", "Distractor Mix"))
        self.TargDist_11.setItemText(2, _translate("MainWindow", "None"))
        self.TargDist_12.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_12.setItemText(1, _translate("MainWindow", "Distractor Mix"))
        self.TargDist_12.setItemText(2, _translate("MainWindow", "Purge"))
        self.TargDist_12.setItemText(3, _translate("MainWindow", "None"))
        self.TargDist_10.setItemText(0, _translate("MainWindow", "Distractor"))
        self.TargDist_10.setItemText(1, _translate("MainWindow", "Distractor Mix"))
        self.TargDist_10.setItemText(2, _translate("MainWindow", "None"))
        self.TargDist_7.setItemText(0, _translate("MainWindow", "Distractor"))
        self.label_77.setText(_translate("MainWindow", "Valve 9"))
        self.label_76.setText(_translate("MainWindow", "Valve 8"))
        self.label_75.setText(_translate("MainWindow", "Target or Distractor"))
        self.label_78.setText(_translate("MainWindow", "Odor"))
        self.EditOdorList.setText(_translate("MainWindow", "Edit Odor List?"))
        self.SubmitOdors.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Odors"))
        self.label_6.setText(_translate("MainWindow", "Day Session"))
        self.label_3.setText(_translate("MainWindow", "Session"))
        self.label_18.setText(_translate("MainWindow", "Trial Time (s)"))
        self.NumberofTrials.setCurrentText(_translate("MainWindow", "10"))
        self.NumberofTrials.setItemText(0, _translate("MainWindow", "10"))
        self.NumberofTrials.setItemText(1, _translate("MainWindow", "20"))
        self.NumberofTrials.setItemText(2, _translate("MainWindow", "30"))
        self.NumberofTrials.setItemText(3, _translate("MainWindow", "40"))
        self.NumberofTrials.setItemText(4, _translate("MainWindow", "50"))
        self.NumberofTrials.setItemText(5, _translate("MainWindow", "60"))
        self.label_35.setText(_translate("MainWindow", "Add random alert Time"))
        self.label_17.setText(_translate("MainWindow", "Number of Trials"))
        self.label_2.setText(_translate("MainWindow", "Alert Time"))
        self.GenProbes.setItemText(0, _translate("MainWindow", "0"))
        self.GenProbes.setItemText(1, _translate("MainWindow", "2"))
        self.GenProbes.setItemText(2, _translate("MainWindow", "4"))
        self.GenProbes.setItemText(3, _translate("MainWindow", "6"))
        self.GenProbes.setItemText(4, _translate("MainWindow", "8"))
        self.label_5.setText(_translate("MainWindow", "Use Tones"))
        self.OdorPrev.setCurrentText(_translate("MainWindow", "1.0"))
        self.OdorPrev.setItemText(0, _translate("MainWindow", "1.0"))
        self.OdorPrev.setItemText(1, _translate("MainWindow", "0.9"))
        self.OdorPrev.setItemText(2, _translate("MainWindow", "0.8"))
        self.OdorPrev.setItemText(3, _translate("MainWindow", "0.7"))
        self.OdorPrev.setItemText(4, _translate("MainWindow", "0.6"))
        self.OdorPrev.setItemText(5, _translate("MainWindow", "0.5"))
        self.OdorPrev.setItemText(6, _translate("MainWindow", "0.4"))
        self.OdorPrev.setItemText(7, _translate("MainWindow", "0.3"))
        self.OdorPrev.setItemText(8, _translate("MainWindow", "0.2"))
        self.OdorPrev.setItemText(9, _translate("MainWindow", "0.1"))
        self.OdorPrev.setItemText(10, _translate("MainWindow", "0.05"))
        self.OdorPrev.setItemText(11, _translate("MainWindow", "0"))
        self.AutoScore.setItemText(0, _translate("MainWindow", "Yes"))
        self.AutoScore.setItemText(1, _translate("MainWindow", "No"))
        self.label_15.setText(_translate("MainWindow", "Reinforce Targets"))
        self.ReinforceTargets.setItemText(0, _translate("MainWindow", "1.0"))
        self.ReinforceTargets.setItemText(1, _translate("MainWindow", "0.9"))
        self.ReinforceTargets.setItemText(2, _translate("MainWindow", "0.8"))
        self.ReinforceTargets.setItemText(3, _translate("MainWindow", "0.7"))
        self.ReinforceTargets.setItemText(4, _translate("MainWindow", "0.6"))
        self.ReinforceTargets.setItemText(5, _translate("MainWindow", "0.5"))
        self.ReinforceTargets.setItemText(6, _translate("MainWindow", "0.4"))
        self.ReinforceTargets.setItemText(7, _translate("MainWindow", "0.3"))
        self.ReinforceTargets.setItemText(8, _translate("MainWindow", "0.2"))
        self.ReinforceTargets.setItemText(9, _translate("MainWindow", "0.1"))
        self.ReinforceTargets.setItemText(10, _translate("MainWindow", "0.0"))
        self.WaitforCorrect.setItemText(0, _translate("MainWindow", "No"))
        self.WaitforCorrect.setItemText(1, _translate("MainWindow", "Yes"))
        self.Context.setItemText(0, _translate("MainWindow", "Yes"))
        self.Context.setItemText(1, _translate("MainWindow", "No"))
        self.SaveSettings.setText(_translate("MainWindow", "Save Settings"))
        self.label_13.setText(_translate("MainWindow", "Reinforce Blanks"))
        self.label_16.setText(_translate("MainWindow", "Wait for a Correct Response? "))
        self.ReinforceBlanks.setCurrentText(_translate("MainWindow", "1.00"))
        self.ReinforceBlanks.setItemText(0, _translate("MainWindow", "1.00"))
        self.ReinforceBlanks.setItemText(1, _translate("MainWindow", "0.90"))
        self.ReinforceBlanks.setItemText(2, _translate("MainWindow", "0.80"))
        self.ReinforceBlanks.setItemText(3, _translate("MainWindow", "0.70"))
        self.ReinforceBlanks.setItemText(4, _translate("MainWindow", "0.60"))
        self.ReinforceBlanks.setItemText(5, _translate("MainWindow", "0.50"))
        self.ReinforceBlanks.setItemText(6, _translate("MainWindow", "0.40"))
        self.ReinforceBlanks.setItemText(7, _translate("MainWindow", "0.30"))
        self.ReinforceBlanks.setItemText(8, _translate("MainWindow", "0.20"))
        self.ReinforceBlanks.setItemText(9, _translate("MainWindow", "0.10"))
        self.ReinforceBlanks.setItemText(10, _translate("MainWindow", "0.00"))
        self.label_20.setText(_translate("MainWindow", "Odor Line"))
        self.label_23.setText(_translate("MainWindow", "Handler Blind"))
        self.label_36.setText(_translate("MainWindow", "Air Line"))
        self.label_12.setText(_translate("MainWindow", "Target Odor Frequency"))
        self.odorLine.setItemText(0, _translate("MainWindow", "0"))
        self.odorLine.setItemText(1, _translate("MainWindow", ".1"))
        self.odorLine.setItemText(2, _translate("MainWindow", ".25"))
        self.odorLine.setItemText(3, _translate("MainWindow", "0.50"))
        self.odorLine.setItemText(4, _translate("MainWindow", "0.75"))
        self.odorLine.setItemText(5, _translate("MainWindow", "1.0"))
        self.label_26.setText(_translate("MainWindow", "Notes"))
        self.label_24.setText(_translate("MainWindow", "Auto Score Alerts"))
        self.HandlerBlind.setItemText(0, _translate("MainWindow", "Yes"))
        self.HandlerBlind.setItemText(1, _translate("MainWindow", "No"))
        self.airLine.setItemText(0, _translate("MainWindow", "0"))
        self.airLine.setItemText(1, _translate("MainWindow", "0.1"))
        self.airLine.setItemText(2, _translate("MainWindow", "0.25"))
        self.airLine.setItemText(3, _translate("MainWindow", "0.5"))
        self.airLine.setItemText(4, _translate("MainWindow", "1"))
        self.airLine.setItemText(5, _translate("MainWindow", "1.5"))
        self.airLine.setItemText(6, _translate("MainWindow", "2"))
        self.airLine.setItemText(7, _translate("MainWindow", "2.5"))
        self.airLine.setItemText(8, _translate("MainWindow", "3"))
        self.label_19.setText(_translate("MainWindow", "N Generalization Trials"))
        self.Submit.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Session Settings"))
        self.response_2.setText(_translate("MainWindow", "2"))
        self.response_4.setText(_translate("MainWindow", "4"))
        self.response_1.setText(_translate("MainWindow", "1"))
        self.response_6.setText(_translate("MainWindow", "6"))
        self.response_3.setText(_translate("MainWindow", "3"))
        self.response_5.setText(_translate("MainWindow", "5"))
        self.response_7.setText(_translate("MainWindow", "All Clear"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.infoLabel.setText(_translate("MainWindow", "Updates"))
        self.Response_Box.setItemText(0, _translate("MainWindow", "All Clear"))
        self.Response_Box.setItemText(1, _translate("MainWindow", "Olfactometer1"))
        self.Response_Box.setItemText(2, _translate("MainWindow", "Olfactometer2"))
        self.Response_Box.setItemText(3, _translate("MainWindow", "Olfactometer3"))
        self.Response_Box.setItemText(4, _translate("MainWindow", "Olfactometer4"))
        self.Response_Box.setItemText(5, _translate("MainWindow", "Olfactometer5"))
        self.Response_Box.setItemText(6, _translate("MainWindow", "Olfactometer6"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Trial Status"))
        self.Position1.setText(_translate("MainWindow", "Odor Line"))
        self.Position3.setText(_translate("MainWindow", "Air Line"))
        self.Position1_2.setText(_translate("MainWindow", "Setting 1"))
        self.Position1_3.setText(_translate("MainWindow", "Setting 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Threshold Setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Session Statistics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Basic Statistics"))
        self.label.setText(_translate("MainWindow", "Valve 7"))
        self.label_32.setText(_translate("MainWindow", "Valve 4"))
        self.ResetOdors.setText(_translate("MainWindow", "Re-set Odor Names"))
        self.label_33.setText(_translate("MainWindow", "Valve 5"))
        self.label_31.setText(_translate("MainWindow", "Valve 3"))
        self.label_25.setText(_translate("MainWindow", "Valve 1"))
        self.label_30.setText(_translate("MainWindow", "Valve 2"))
        self.label_34.setText(_translate("MainWindow", "Valve 6"))
        self.label_4.setText(_translate("MainWindow", "Valve 8"))
        self.label_7.setText(_translate("MainWindow", "Valve 9"))
        self.label_60.setText(_translate("MainWindow", "Valve 11"))
        self.label_38.setText(_translate("MainWindow", "Valve 10"))
        self.label_61.setText(_translate("MainWindow", "Valve 12"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Edit Odors"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionsave_as_default.setText(_translate("MainWindow", "save as default"))
        self.actionset_directory.setText(_translate("MainWindow", "set directory"))
        self.actionset_data_folder.setText(_translate("MainWindow", "set data folder"))

